version: '3.2'

services:
    mysql-exporter:
        image: prom/mysqld-exporter
        container_name: mysql-exporter
        hostname: mysql-exporter
        restart: always
        ports:
            - "9104:9104"
        networks:
            - web              
#        network_mode: "host"
        environment:
            DATA_SOURCE_NAME: "exporter:123456@(192.168.10.60:3306)/"
#networks:
#    exporter:
#      driver: host      

networks:
  web:
    external: true # 不创建network
